// <auto-generated />
namespace code.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_user_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_user_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201501011545364_add_user_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
